const crypto=require('crypto');
const db=require('./db');
const uid=()=>crypto.randomUUID();
async function settings(guildId){let row=await db.prepare('SELECT * FROM radio_settings WHERE guild_id=?').get(guildId);if(!row){await db.prepare("INSERT INTO radio_settings(guild_id) VALUES(?) ON CONFLICT(guild_id) DO NOTHING").run(guildId);row=await db.prepare('SELECT * FROM radio_settings WHERE guild_id=?').get(guildId);}return row;}
async function configure(guildId,{frequency,channelId,stationName}){const f=String(frequency||'87.8 MHz').trim().slice(0,20),c=String(channelId||'').trim().slice(0,30),n=String(stationName||'DAYZ GATE RADIO').trim().slice(0,80);await db.prepare("INSERT INTO radio_settings(guild_id,frequency,channel_id,station_name) VALUES(?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET frequency=excluded.frequency,channel_id=excluded.channel_id,station_name=excluded.station_name,updated_at=CURRENT_TIMESTAMP").run(guildId,f,c,n);return settings(guildId);}
async function history(guildId,limit=30){return db.prepare('SELECT * FROM radio_messages WHERE guild_id=? ORDER BY created_at DESC LIMIT ?').all(guildId,Math.max(1,Math.min(100,Number(limit)||30)));}
async function add(guildId,authorId,message,kind='hq',frequency){const cfg=await settings(guildId),id=uid(),text=String(message||'').trim().slice(0,1800);if(!text)throw new Error('Message radio vide.');kind=['hq','ambiance','alerte'].includes(kind)?kind:'hq';await db.prepare('INSERT INTO radio_messages(id,guild_id,author_id,kind,message,frequency) VALUES(?,?,?,?,?,?)').run(id,guildId,String(authorId||''),kind,text,String(frequency||cfg.frequency||'87.8 MHz'));return db.prepare('SELECT * FROM radio_messages WHERE id=?').get(id);}
function format(row,cfg){const prefix=row.kind==='ambiance'?'📻':row.kind==='alerte'?'🚨':'📡';const label=row.kind==='ambiance'?'Transmission':row.kind==='alerte'?'Alerte':'DAYZ GATE HQ';return `${prefix} **${cfg.station_name||'DAYZ GATE RADIO'} · ${row.frequency||cfg.frequency}**\n${label} : ${row.message}`;}
async function send(client,guildId,authorId,message,kind='hq'){const cfg=await settings(guildId);if(!cfg.channel_id)throw new Error('Configure d’abord le salon radio.');const row=await add(guildId,authorId,message,kind,cfg.frequency);const ch=await client.channels.fetch(cfg.channel_id);if(!ch?.isTextBased())throw new Error('Salon radio introuvable.');await ch.send({content:format(row,cfg),allowedMentions:{parse:[]}});return row;}
async function recurringAdd(guildId,channelId,createdBy,message,intervalMinutes){const minutes=Math.max(5,Math.min(10080,Number(intervalMinutes)||60)),id=uid(),next=Date.now()+minutes*60000,text=String(message||'').trim().slice(0,1800);if(!text)throw new Error('Message vide.');await db.prepare('INSERT INTO recurring_messages(id,guild_id,channel_id,message,interval_minutes,next_run_at,created_by) VALUES(?,?,?,?,?,?,?)').run(id,guildId,channelId,text,minutes,next,String(createdBy||''));return {id,minutes,next};}
async function recurringList(guildId){return db.prepare('SELECT * FROM recurring_messages WHERE guild_id=? ORDER BY created_at DESC').all(guildId);}
async function recurringDelete(guildId,id){return db.prepare('DELETE FROM recurring_messages WHERE guild_id=? AND id=?').run(guildId,id);}
function scope(req){return req.session.role==='founder'?req.session.guildId:(req.session.selectedGuildId||req.session.guildId||'owner')}
function mount(app,mustBeLoggedIn,discordClient){
 app.get('/api/radio',mustBeLoggedIn,async(req,res)=>{const gid=scope(req);res.json({settings:await settings(gid),history:await history(gid,50),recurring:await recurringList(gid)})});
 app.post('/api/radio/settings',mustBeLoggedIn,async(req,res)=>res.json(await configure(scope(req),req.body||{})));
 app.post('/api/radio/send',mustBeLoggedIn,async(req,res)=>res.json(await send(discordClient,scope(req),req.session.discordUserId||req.session.admin,req.body?.message,req.body?.kind||'hq')));
 app.post('/api/radio/recurring',mustBeLoggedIn,async(req,res)=>res.json(await recurringAdd(scope(req),String(req.body?.channelId||''),req.session.discordUserId||req.session.admin,req.body?.message,req.body?.intervalMinutes)));
 app.delete('/api/radio/recurring/:id',mustBeLoggedIn,async(req,res)=>{await recurringDelete(scope(req),req.params.id);res.json({ok:true})});
}
function start(client){let busy=false;async function tick(){if(busy)return;busy=true;try{const rows=await db.prepare('SELECT * FROM recurring_messages WHERE enabled=1 AND next_run_at<=? ORDER BY next_run_at LIMIT 30').all(Date.now());for(const r of rows){try{const ch=await client.channels.fetch(r.channel_id);if(!ch?.isTextBased())throw new Error('Salon inaccessible');await ch.send({content:`⏰ **Rappel récurrent**\n${r.message}`,allowedMentions:{parse:[]}});await db.prepare('UPDATE recurring_messages SET next_run_at=? WHERE id=?').run(Date.now()+Number(r.interval_minutes)*60000,r.id);}catch(e){console.error('Rappel récurrent :',e.code||e.message)}}}finally{busy=false}}tick();const timer=setInterval(tick,60000);timer.unref();return timer;}
module.exports={settings,configure,history,add,send,format,recurringAdd,recurringList,recurringDelete,start,mount};